language: python
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - python3 -m pytest --cov=pytest-test/
after_success:
  - coveralls
notifications:
  email: false
