language: python
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install unittest
  - pip install coveralls
script:
  - coverage erase && coverage run -m unittest discover && coverage report -m
after_success:
  - coveralls
notifications:
  email: false
